#!/bin/bash
# Star - Morph Package & Config Manager
# Usage: star spawn <data.fall>

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

if [ "$1" != "spawn" ]; then
    echo "Usage: star spawn <data.fall>"
    exit 1
fi

INPUT_FILE="$2"

if [ -z "$INPUT_FILE" ]; then
    echo "Error: No .fall file specified."
    exit 1
fi

if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: File '$INPUT_FILE' not found."
    exit 1
fi

echo "⭐️ Star spawning from $INPUT_FILE..."

CONFIG_OUT="config.mk"
echo "# Generated by Star" > "$CONFIG_OUT"

while IFS=':' read -r key value; do
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)

    if [[ "$key" =~ ^# ]] || [ -z "$key" ]; then continue; fi

    case "$key" in
        "vps_host") echo "VPS_HOST=$value" >> "$CONFIG_OUT" ;;
        "vps_user") echo "VPS_USER=$value" >> "$CONFIG_OUT" ;;
        "vps_pass") echo "VPS_PASS=$value" >> "$CONFIG_OUT" ;;
        "vps_dir")  echo "VPS_DIR=$value"  >> "$CONFIG_OUT" ;;
        "compiler") echo "MORPH_COMPILER=$value" >> "$CONFIG_OUT" ;;
    esac
done < "$INPUT_FILE"

echo -e "${GREEN}Success! Configuration spawned to $CONFIG_OUT${NC}"
