#!/bin/bash
# Morph Source Merger
# Combines all Fox source files into one monolithic file for compilation

OUTPUT="build/morph_monolithic.fox"

echo "=== Morph Source Merger ==="

cat > "$OUTPUT" << 'EOF'
; ============================================================================
; MORPH SELF-HOSTED COMPILER - MONOLITHIC BUILD
; Generated by tools/merge_source.sh
; ============================================================================

EOF

# Order matters! Dependencies first

# 1. Standard library
echo "; === STANDARD LIBRARY ===" >> "$OUTPUT"
for f in lib/buffer.fox lib/file_io.fox lib/format.fox lib/hashmap.fox lib/vector.fox lib/string_utils.fox; do
    echo "" >> "$OUTPUT"
    echo "; --- $(basename $f) ---" >> "$OUTPUT"
    # Remove Ambil/Daftar/indeks lines, keep only code
    grep -v "^Ambil\|^Daftar\|^indeks\|^#" "$f" >> "$OUTPUT"
done

# 2. Compiler core
echo "" >> "$OUTPUT"
echo "; === COMPILER CORE ===" >> "$OUTPUT"
for f in apps/compiler/src/globals.fox apps/compiler/src/constants.fox apps/compiler/src/codegen.fox \
         apps/compiler/src/types.fox apps/compiler/src/supplier.fox; do
    echo "" >> "$OUTPUT"
    echo "; --- $(basename $f) ---" >> "$OUTPUT"
    grep -v "^Ambil\|^Daftar\|^indeks\|^#\|^###" "$f" >> "$OUTPUT"
done

# 3. Parser helpers
echo "" >> "$OUTPUT"
echo "; === PARSER HELPERS ===" >> "$OUTPUT"
for f in apps/compiler/src/parser_helpers_*.fox; do
    echo "" >> "$OUTPUT"
    echo "; --- $(basename $f) ---" >> "$OUTPUT"
    grep -v "^Ambil\|^Daftar\|^indeks\|^#\|^###" "$f" >> "$OUTPUT"
done

# 4. Parser dispatchers
echo "" >> "$OUTPUT"
echo "; === PARSER DISPATCHERS ===" >> "$OUTPUT"
for f in apps/compiler/src/parser_dispatch_*.fox; do
    echo "" >> "$OUTPUT"
    echo "; --- $(basename $f) ---" >> "$OUTPUT"
    grep -v "^Ambil\|^Daftar\|^indeks\|^#\|^###" "$f" >> "$OUTPUT"
done

# 5. Main entry point (last, so it can call everything)
echo "" >> "$OUTPUT"
echo "; === MAIN ===" >> "$OUTPUT"
# Extract only the function part from main.fox (skip header and Ambil)
awk '/^fungsi mulai/,/^tutup_fungsi/' apps/compiler/src/main.fox >> "$OUTPUT"

lines=$(wc -l < "$OUTPUT")
echo "Generated: $OUTPUT ($lines lines)"
